# Generated by Django 6.0.4 on 2026-07-22 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productoption_productoptionvalue_productvariation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moq', models.PositiveIntegerField(help_text='Minimum total units required to unlock bulk import.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Bulk unit price once MOQ is met.', max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('moq_reached', 'MOQ Reached'), ('importing', 'Importing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('closes_at', models.DateTimeField(help_text='Last date buyers can join this group buy.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_buys', to='core.product')),
            ],
            options={
                'verbose_name_plural': 'group buys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupBuyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.groupbuy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_buy_entries', to=settings.AUTH_USER_MODEL)),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_buy_entries', to='core.productvariation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('group_buy', 'user'), name='unique_group_buy_entry_per_user')],
            },
        ),
    ]
