# Generated by Django 6.0.4 on 2026-07-22 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_groupbuy_groupbuyentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupbuyentry',
            name='unique_group_buy_entry_per_user',
        ),
        migrations.AddConstraint(
            model_name='groupbuyentry',
            constraint=models.UniqueConstraint(fields=('group_buy', 'user', 'variation'), name='unique_group_buy_entry_per_user_variation'),
        ),
    ]
