# Generated by Django 6.0.4 on 2026-07-22 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_groupbuy_multi_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.productvariation'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.productvariation')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('variation__isnull', True)), fields=('product', 'title'), name='unique_product_level_attribute_title'), models.UniqueConstraint(condition=models.Q(('variation__isnull', False)), fields=('variation', 'title'), name='unique_variation_attribute_title')],
            },
        ),
    ]
