# Generated by Django 6.0.4 on 2026-07-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered from supplier'), ('in_transit', 'In transit'), ('customs', 'In customs'), ('received', 'Received locally'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('supplier_reference', models.CharField(blank=True, help_text='Factory or supplier order reference.', max_length=100)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_buy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_batch', to='core.groupbuy')),
            ],
            options={
                'verbose_name_plural': 'import batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
