# Generated by Django 6.0.4 on 2026-07-23 08:15

from decimal import Decimal

from django.db import migrations, models


def seed_shipping_rates(apps, schema_editor):
    ShippingRate = apps.get_model('core', 'ShippingRate')
    defaults = [
        {
            'mode': 'air',
            'goods_class': 'normal',
            'charge_basis': 'per_kg',
            'rate': Decimal('12.50'),
            'currency': 'USD',
            'notes': 'Default air freight for normal goods',
        },
        {
            'mode': 'air',
            'goods_class': 'special',
            'charge_basis': 'per_kg',
            'rate': Decimal('13.00'),
            'currency': 'USD',
            'notes': 'Default air freight for special goods',
        },
        {
            'mode': 'sea',
            'goods_class': 'normal',
            'charge_basis': 'per_cbm',
            'rate': Decimal('73000'),
            'currency': 'KES',
            'notes': 'Default sea freight per CBM',
        },
        {
            'mode': 'sea',
            'goods_class': 'special',
            'charge_basis': 'per_cbm',
            'rate': Decimal('73000'),
            'currency': 'KES',
            'notes': 'Default sea freight per CBM for special goods',
        },
    ]
    for entry in defaults:
        ShippingRate.objects.update_or_create(
            mode=entry['mode'],
            goods_class=entry['goods_class'],
            defaults=entry,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_productattribute_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special_class',
            field=models.BooleanField(default=False, help_text='Special goods use a higher air freight rate per kg.'),
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('air', 'Air freight'), ('sea', 'Sea freight')], max_length=10)),
                ('goods_class', models.CharField(choices=[('normal', 'Normal goods'), ('special', 'Special goods')], max_length=10)),
                ('charge_basis', models.CharField(choices=[('per_kg', 'Per kilogram'), ('per_cbm', 'Per CBM')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['mode', 'goods_class'],
                'constraints': [models.UniqueConstraint(fields=('mode', 'goods_class'), name='unique_shipping_rate_mode_class')],
            },
        ),
        migrations.RunPython(seed_shipping_rates, migrations.RunPython.noop),
    ]
