# Generated by Django 6.0.4 on 2026-07-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_wishlistitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variation__isnull', True)), fields=('cart', 'group_buy'), name='unique_cart_product_level_item'),
        ),
    ]
