# Generated by Django 6.0.4 on 2026-07-26 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_product_import_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimportdraft',
            name='current_step',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('categories', 'Categories'), ('basics', 'Product details'), ('attributes', 'Specifications'), ('variations', 'Variations & pricing'), ('product_media', 'Product images'), ('variation_media', 'Variation images'), ('review', 'Review & publish')], default='basics', max_length=30),
        ),
        migrations.CreateModel(
            name='UserCategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='unique_user_category_preference')],
            },
        ),
    ]
