# Generated by Django 6.0.4 on 2026-07-26 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_view_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGoTogetherLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go_together_incoming', to='core.category')),
                ('source_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go_together_outgoing', to='core.category')),
            ],
            options={
                'ordering': ['sort_order', 'linked_category__name'],
                'constraints': [models.UniqueConstraint(fields=('source_category', 'linked_category'), name='unique_category_go_together_link'), models.CheckConstraint(condition=models.Q(('source_category', models.F('linked_category')), _negated=True), name='no_self_go_together_link')],
            },
        ),
    ]
