# Generated by Django 6.0.4 on 2026-10-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_import_costing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='shipment',
            field=models.ForeignKey(blank=True, help_text='Optional physical batch grouping many products; costs remain on each import batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='core.importshipment'),
        ),
    ]
